[package]
name = "msg_ring_runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5"
futures = "0.3"

[dev-dependencies]
criterion = { version = "0.5", default-features = false, features = ["cargo_bench_support"] }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time", "macros"] }

[target.'cfg(target_os = "linux")'.dependencies]
glommio = { version = "0.9", optional = true }
io-uring = "0.7.11"

[features]
default = []
glommio-bench = ["dep:glommio"]

[[bench]]
name = "ping_pong"
harness = false
